Add Hangman Game
Koch-Dustin/Galgenmaennchen pull request #1
Opened 2022-11-18 11:53 UTC by Koch-Dustin

Changes:
   - Add Hangman

PR: #1

2022-11-18 12:02 UTC, Nicojele requested changes

2022-11-18 12:02 UTC, Nicojele commented on Hangman.py
> +play(GetRandomWordFromWordList())
add End of File

2022-11-18 12:02 UTC, Nicojele commented on HangmanStages.py
> +      return stages[tries]
add End of File

2022-11-21 14:19 UTC, DevBastiS approved these changes

2022-11-21 14:19 UTC, DevBastiS commented on Hangman.py
> +
```suggestion
  
```

2022-11-21 14:19 UTC, DevBastiS commented on Hangman.py
> +
```suggestion
        
```

2022-11-22 12:05 UTC, Nicojele approved these changes

2022-11-22 12:33 UTC, merged